---
title: Sponsors
---


# Sponsors of Distance

The following organizations have provided support for Distance software.  If you are interested in helping to support distance, or funding development of specific features, [please contact us](/contact.html).

## Major sponsor

* [Wildlife Conservation Society](http://wcs.org/) for 3 years was the major sponsor of Distance, providing funding to enable ongoing support and development of the software. 

## Features sponsors

In addition, specific features in Distance have been or are being developed through contracts or grants from:

- [Living Marine Resources program, US Navy, Chief of Naval Operations, Energy and Environmental Readiness Division (N45)](https://www.navfac.navy.mil/lmr)
- [US Office of Naval Research](http://www.onr.navy.mil), [Marine Life Sciences program](http://www.onr.navy.mil/sci_tech/32/322/marine_life_sciences/marine_life_sciences.asp)
- [GeoMarine Inc](http://www.geo-marine.com/) Geo-Marine was acquired by Versar Inc. in 2013.
- [US National Marine Mammal Laboratory](https://www.fisheries.noaa.gov/about/marine-mammal-laboratory)
- [Fisheries and Oceans Canada](http://www.dfo-mpo.gc.ca/), [Arctic Research Division](http://www.dfo-mpo.gc.ca/regions/central/science/arcres/index_e.htm)
- [US National Parks Service, Inventory and Monitoring Division](https://www.nps.gov/im/index.htm)
- [Colorado Cooperative Fish and Wildlife Research Unit]([https://www.coopunits.org/Colorado/](https://warnercnr.colostate.edu/fwcb/cooperative-fish-wildlife-research-unit/)
- [UK Biotechnology and Biological Sciences Research Council](http://www.bbsrc.ac.uk/)
- [UK Engineering and Physical Sciences Research Council](http://www.epsrc.ac.uk/)
