---
title: History
---

# Distance history

Distance evolved from program TRANSECT. However, Distance is quite different from its predecessor as a result of changes in analysis methods and expanded capabilities. The name Distance was chosen because it can be used to analyze several forms of distance sampling data: line transect, point transect (variable circular plot) and cue-counts. By contrast TRANSECT was designed only to analyze line transect data.

Distance versions 1.0 - 2.2 were DOS-based applications that were programmed using a relatively simple command language. Version 3.0 was a windows console application, but retained the command language structure. All of these versions were principally programmed by Jeff Laake of the National Marine Mammal Laboratory, US Fisheries Service.

In 1997, Steve Buckland and David Borchers, from the University of St Andrews, obtained funding from two British research councils to proceed with an ambitious three-year project to develop new distance sampling software. The new software, which became known as Distance 4, was designed to be fully windows-based, and be capable of incorporating new features such as geographic survey design, multiple covariate distance sampling models, spatial estimation of abundance, and dual observer mark-recapture line transect methods. A Distance 4 project development team was assembled, coordinated by Len Thomas. In autumn 1997, it was decided to produce an intermediate version of Distance: fully windows based, but with the same analysis capabilities as the current version 3.0. This new program, Distance 3.5, took one full year to develop, and was released in November 1998, with various updates through to February 1999. Distance 3.5 was downloaded by over 4000 users, from around 120 countries. 

Extension of Distance 3.5 to become Distance 4 began in 1999, and the software was first previewed at training workshops in summer 2000. 

- After various public beta versions, Distance 4.0 was released in 2002, followed by Distance 4.1 in 2003 and Distance 5.0 in 2006. This last version had a major new feature in the form of a link to the free statistical software R, thereby facilitating a major expansion in the analytical capabilities available to Distance users. 
- Distance 6.0 made use of this feature to include a new density surface modelling analysis engine, written as a library in R. Distance 6 was released in July 2009, with Distance 6.2 (containing new features and bug releases) following in May 2014.  
- October 2016 brought the release of Distance 7, including the new simulation engine and multi-analysis engine. Distance 7.1 (July 2017) contained some new features; Distance 7.2 (June 2018) included the addition of point transect analyses in both MRDS and DSM; Distance 7.3 (February 2019) added a Shape Import Wizard; Distance 7.4 (May 2022) added features to analyze Camera Trap Distance Sampling data; and Distance 7.5 (September 2022) marked a switch from 32-bit to 64-bit R for the R-based engines.

We are still actively developing the software, incorporating new features and extending current ones. If you have any comments or suggestions about the program, [we’d love to hear from you!](/contact.html)


## Development team alumni

The below people have been involved in the development of Distance but no-longer take an active role on the team (though may still be working on distance sampling related issues).

- **David R. Anderson** passed away in 2020.  He was formerly Leader of the Colorado Cooperative Fish and Wildlife Research Unit, USA, before retiring in May 2003 and becoming emeratus Professor of Fishery and Wildlife Biology at Colorado State University.
- **Jon Bishop** was formerly a post-doctoral research fellow within CREEM at the University of St Andrews and now works at the University of Birmingham.
- **Kenneth P. Burnham** is emeratus Professor of Biological Statistics at Colorado State University, Fort Collins, USA, and was formerly Assistant Leader of the Colorado Cooperative Fish and Wildlife Research Unit.
- **Sharon L. Hedley** is a consultant statistician based in Fife, Scotland.
- **Fernanda Marques** works for Funbio (Brazilian Biodiversity Fund) in Brazil. She was formerly a graduate student in the School of Mathematics and Statistics, University of St. Andrews.
- **Dave Miller** is a research statistician with Biomathematics and Statistics Scotland.
- **John H. Pollard** is a software engineer and was also formerly a graduate student in the School of Mathematics and Statistics at the University of St. Andrews.
- **Samantha Strindberg** is a quantitative ecologist working in the Living Landscapes Program at the Wildlife Conservation Society, New York, USA. She was formerly a graduate student in the School of Mathematics and Statistics, University of St. Andrews, Scotland.


